export default {
	'EDIT_ITEM_FIELD' : 'EDIT_ITEM_FIELD',
	'TOGGLE_PAYMENT_TYPE' : 'TOGGLE_PAYMENT_TYPE',
	'SUBMIT_ITEM' : 'SUBMIT_ITEM',
	'SUBMIT_ITEM_SUCCESS' : 'SUBMIT_ITEM_SUCCESS',
	'SUBMIT_ITEM_ERROR' : 'SUBMIT_ITEM_ERROR',
	'HIDE_NOTIFICATION' : 'HIDE_NOTIFICATION',

	'FETCH_ITEMS' : 'FETCH_ITEMS',
	'FETCH_ITEMS_SUCCESS' : 'FETCH_ITEMS_SUCCESS',
	'FETCH_ITEMS_ERROR' : 'FETCH_ITEMS_ERROR',
	'SET_ITEMS' : 'SET_ITEMS'
};