export default {
	'EDIT_ITEM_FIELD' : 'EDIT_ITEM_FIELD',
	'TOGGLE_PAYMENT_TYPE' : 'TOGGLE_PAYMENT_TYPE',
	'SUBMIT_ITEM' : 'SUBMIT_ITEM',
	'SUBMIT_ITEM_SUCCESS' : 'SUBMIT_ITEM_SUCCESS',
	'SUBMIT_ITEM_ERROR' : 'SUBMIT_ITEM_ERROR',

	'FETCH_ITEMS' : 'FETCH_ITEMS',
	'FETCH_ITEMS_SUCCESS' : 'FETCH_ITEMS_SUCCESS',
	'FETCH_ITEMS_ERROR' : 'FETCH_ITEMS_ERROR',
	'SET_ITEMS' : 'SET_ITEMS',
	'SET_PAGINATION_OFFSET' : 'SET_PAGINATION_OFFSET',

	'SET_ITEM' : 'SET_ITEM',
	'SET_ITEM_ERROR' : 'SET_ITEM_ERROR',
	'RESET_ITEM' : 'RESET_ITEM',

	'DELETE_ITEM' : 'DELETE_ITEM',
	'DELETE_ITEM_SUCCESS' : 'DELETE_ITEM_SUCCESS',
	'DELETE_ITEM_ERROR' : 'DELETE_ITEM_ERROR',

	'EDIT_MODE' : 'EDIT_MODE',

	'DISPLAY_ITEM' : 'DISPLAY_ITEM',

	'ONLINE' : 'ONLINE',
	'OFFLINE' : 'OFFLINE',

	'RESET_ACTION_CREATORS' : 'RESET_ACTION_CREATORS',


	'EDIT_BUYER_FIELD' : 'EDIT_BUYER_FIELD',
	'RESET_TRANSACTION' : 'RESET_TRANSACTION',
	'TRANSACTION_SET_ITEM' : 'TRANSACTION_SET_ITEM',
	'TRANSACTION_EDIT_MODE' : 'TRANSACTION_EDIT_MODE',
	'TRANSACTION_DISPLAY_ITEM' : 'TRANSACTION_DISPLAY_ITEM',
	'TRANSACTION_EDIT_QUANTITY' : 'TRANSACTION_EDIT_QUANTITY',
	'TRANSACTION_EDIT_PAYMENT_TYPE' : 'TRANSACTION_EDIT_PAYMENT_TYPE'

};